// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package train_db

import ()

type UserPreference struct {
	ID                   int64
	StationID            string
	StationPage          int64
	UniqueConstantColumn int64
}
