// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package train_db

import ()

type UserActivity struct {
	ID          int64
	StationPage int64
}

type UserPreference struct {
	ID        int64
	StationID string
}
