// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package train_db

import (
	"context"
)

const setStationId = `-- name: SetStationId :one
INSERT INTO user_preferences (
  station_id
) VALUES (
  ?
)
RETURNING station_id
`

func (q *Queries) SetStationId(ctx context.Context, stationID string) (string, error) {
	row := q.db.QueryRowContext(ctx, setStationId, stationID)
	var station_id string
	err := row.Scan(&station_id)
	return station_id, err
}
