// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {train} from '../models';
import {context} from '../models';
import {app} from '../models';
import {train_db} from '../models';

export function GetCurrentStationPage():Promise<number>;

export function GetIncidents():Promise<train.IncidentsResponse>;

export function GetSelectedStation():Promise<train.Station>;

export function GetStations():Promise<train.StationsResponse>;

export function GetTrains():Promise<train.TrainsResponse>;

export function InitializeApplicationServices(arg1:context.Context,arg2:app.Config,arg3:train_db.Querier):Promise<void>;

export function SetCurrentStationPage(arg1:number):Promise<void>;

export function SetSelectedStation(arg1:string):Promise<void>;
