// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {train} from '../models';

export function GetIncidents():Promise<train.IncidentsResponse>;

export function GetStations():Promise<train.StationsResponse>;

export function GetTrainsByStationId(arg1:string):Promise<train.TrainsResponse>;
