// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['app']['App']['Close']();
}

export function GetCurrentStationPage() {
  return window['go']['app']['App']['GetCurrentStationPage']();
}

export function GetIncidents() {
  return window['go']['app']['App']['GetIncidents']();
}

export function GetSelectedStation() {
  return window['go']['app']['App']['GetSelectedStation']();
}

export function GetStations() {
  return window['go']['app']['App']['GetStations']();
}

export function GetTrains() {
  return window['go']['app']['App']['GetTrains']();
}

export function InitializeApplicationServices(arg1, arg2, arg3) {
  return window['go']['app']['App']['InitializeApplicationServices'](arg1, arg2, arg3);
}

export function SetCurrentStationPage(arg1) {
  return window['go']['app']['App']['SetCurrentStationPage'](arg1);
}

export function SetSelectedStation(arg1) {
  return window['go']['app']['App']['SetSelectedStation'](arg1);
}
