// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {train} from '../models';

export function GetTrainsByStationId(arg1:string):Promise<train.TrainsResponse>;
