// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIncidents() {
  return window['go']['app']['App']['GetIncidents']();
}

export function GetStations() {
  return window['go']['app']['App']['GetStations']();
}

export function GetTrainsByStationId(arg1) {
  return window['go']['app']['App']['GetTrainsByStationId'](arg1);
}
