name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  # golangci:
  #   name: Lint Wails Go Application
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.21"
  #         cache: false
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         # Require: The version of golangci-lint to use.
  #         # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
  #         # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
  #         version: v1.54
  # test:
  #   name: Test Wails Go Application
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.21"
  #         cache: false
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Run tests
  #       run: go test

  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
            { name: wailsTest, platform: linux/amd64, os: ubuntu-latest },
            # { name: wailsTest, platform: windows/amd64, os: windows-latest },
            # { name: wailsTest, platform: darwin/universal, os: macos-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.21"
          node-version: "20.5.1"
